# Generated by Django 3.1.2 on 2020-10-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='enddatetime',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='startdatetime',
            field=models.DateTimeField(blank=True, verbose_name='开始时间'),
        ),
    ]
