# Generated by Django 3.1.2 on 2020-10-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_tpackage_tpkdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tpackage',
        ),
        migrations.DeleteModel(
            name='TpkDetail',
        ),
    ]
