# Generated by Django 3.1.2 on 2020-10-12 08:48

from django.db import migrations, models
import merchant.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20201011_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picpath', models.ImageField(upload_to=merchant.models.pic_path, verbose_name='引用路径')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='引用次数')),
            ],
        ),
    ]
