# Generated by Django 3.1.2 on 2020-10-26 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20201026_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpackage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('introduct', models.CharField(max_length=500, verbose_name='套餐简介')),
            ],
        ),
        migrations.CreateModel(
            name='TpkDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(verbose_name='开始时间')),
                ('endtime', models.TimeField(verbose_name='结束时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.business')),
            ],
        ),
    ]
