# Generated by Django 3.1.2 on 2020-10-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_picctrl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicCtrl',
        ),
    ]
