# Generated by Django 3.1.2 on 2020-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_delete_picctrl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.AddField(
            model_name='goods',
            name='introduct',
            field=models.CharField(max_length=500, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='sell',
            name='price',
            field=models.FloatField(default=999, verbose_name='价格'),
        ),
    ]
