# Generated by Django 3.1.2 on 2020-10-18 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('type', models.PositiveIntegerField(choices=[(0, '管理员'), (1, '核销员'), (2, '商户')], default=1, verbose_name='类型')),
                ('status', models.PositiveIntegerField(choices=[(0, '禁用'), (1, '离线'), (2, '在线')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
