# Generated by Django 3.1.2 on 2020-10-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vofficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.business', verbose_name='商户id')),
                ('vuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='核销员id')),
            ],
        ),
    ]
