# Generated by Django 3.1.2 on 2020-10-17 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f4875c7c-12c9-4c4a-bbc2-31d4ee06b953'), primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('receiver', models.CharField(max_length=40, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('remarks', models.CharField(max_length=200, verbose_name='备注')),
                ('totalprice', models.FloatField(verbose_name='总价')),
                ('business_name', models.CharField(max_length=50, verbose_name='商家名')),
                ('business_location', models.CharField(max_length=128, verbose_name='地址')),
                ('business_pic', models.ImageField(blank=True, upload_to='', verbose_name='图片地址')),
                ('orderstatus', models.PositiveIntegerField(choices=[(0, '未发货'), (1, '已发货'), (2, '异常')], default=0, verbose_name='订单状态')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant.business', verbose_name='商家')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('openid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='openid')),
                ('sessionid', models.UUIDField(default=uuid.UUID('64841160-588b-44a6-92b9-d7ac137e8631'), verbose_name='sessionid')),
                ('session_key', models.CharField(max_length=32, verbose_name='session_key')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtualcode', models.URLField(verbose_name='虚拟码')),
                ('usingstatus', models.PositiveIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, verbose_name='使用状态')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('goods_pic', models.ImageField(blank=True, upload_to='', verbose_name='图片地址')),
                ('goods_price', models.FloatField(verbose_name='价格')),
                ('goods_count', models.PositiveIntegerField(verbose_name='数量')),
                ('startdatetime', models.DateTimeField(verbose_name='开始时间')),
                ('enddatetime', models.DateTimeField(verbose_name='结束时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchant.goods', verbose_name='商品ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order', verbose_name='订单ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.tourist', verbose_name='游客ID'),
        ),
    ]
