# Generated by Django 3.1.2 on 2020-10-13 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('openid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='openid')),
                ('sessionid', models.UUIDField(default=uuid.UUID('3ac986e3-dae6-47e1-a4fe-74aac82dff03'), verbose_name='sessionid')),
                ('session_key', models.CharField(max_length=32, verbose_name='session_key')),
            ],
        ),
    ]
