# Generated by Django 3.1.2 on 2020-10-17 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='business_pic',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('910eaae0-0de9-4577-9b47-26af8ebf97a2'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('6753fe57-ab0e-4e2e-a999-df40d3bdf67d'), verbose_name='sessionid'),
        ),
    ]
