# Generated by Django 3.1.2 on 2020-10-26 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('994ceea8-8eab-448e-a570-12fbda5d6227'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9476f747-35d0-43fd-96bf-0c191648b0f0'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('e55535d2-7f6d-499e-81ce-56452f7f39d2'), verbose_name='sessionid'),
        ),
    ]
