# Generated by Django 3.1.2 on 2020-10-15 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('7e157f03-2177-4626-8191-fdf3cc2a053c'), verbose_name='sessionid'),
        ),
    ]
