# Generated by Django 3.1.2 on 2020-10-26 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201026_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc82013e-ad7d-4832-a2c4-2a84b830d7c8'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab4d066a-a6d9-4211-970d-cf58831ee573'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('d8eeca51-951e-4ae7-94a4-f181e09695e1'), verbose_name='sessionid'),
        ),
    ]
