# Generated by Django 3.1.2 on 2020-10-26 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201026_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ffd5af9-4fbc-4b0c-872e-781319ad4177'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d0291ee-892b-4cb9-a844-b32fc3abcb9e'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('cbd44aca-9ba7-4d3c-a39a-57bbc61fc0dc'), verbose_name='sessionid'),
        ),
    ]
