# Generated by Django 3.1.2 on 2020-10-18 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201017_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7561c99b-e05e-4141-a3ea-5efdc6520f6a'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cc71b0f-30e7-4be2-bd33-acac103d988b'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('e8bec082-6a25-46b0-8dad-886eff77c392'), verbose_name='sessionid'),
        ),
    ]
