# Generated by Django 3.1.2 on 2020-10-18 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201018_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e187374a-703a-4403-b511-e2f19daa911f'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c46b2c3-3a6a-4be8-8dd4-529f7ee739d3'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('202bc23f-c818-4276-8b87-8e9d1953c275'), verbose_name='sessionid'),
        ),
    ]
