# Generated by Django 3.1.2 on 2020-10-26 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201026_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('822a739f-674c-4290-bfbe-90f6987052f2'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b74d8798-672c-4785-bd9a-056b06a3e309'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('2b5bd689-c0de-407b-9637-0dee7f9b233e'), verbose_name='sessionid'),
        ),
    ]
