# Generated by Django 3.1.2 on 2020-10-18 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201018_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9d400a0-494f-4996-9420-1980172d6deb'), primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f929d407-62e2-418a-bc1e-7e955de93f68'), primary_key=True, serialize=False, verbose_name='订单详细ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='sessionid',
            field=models.UUIDField(default=uuid.UUID('81e57e4c-e50c-4213-a893-73881f490e08'), verbose_name='sessionid'),
        ),
    ]
